export const BANK_NAMES = [
  'OTHER (CUSTOM NAME)',
  'CIBC',
  'Wells Fargo',
  'Scotiabank',
  'Bank of America',
  'TD',
  'BMO',
  'HSBC',
  'RBC',
  'Chase',
  'AMEX',
  'Regions',
  'Capitec',
  'Home Depot',
  'RBS',
  'Desjardins',
  'U.S. Bank',
  'Capital One',
  'Fifth Third Bank',
  'Comerica',
  'Manulife Bank',
  'Tangerine',
  'Paypal',
  'ATB',
  'Citibank'
]