import faker from 'faker';

export const credit_descriptions = [
  'ETRSFR #10005 CIA.GOV',
  'XERO SOFTWARE C PAY BIG',
  'DEPOSIT #109872222 UNILEVER',
  'STEAM SALE #GR56773',
  'DEPOSIT #10284345 CONNAUGHT RD HSBC',
  'ETRSFR #5742734 CIA.GOV',
  'ETRSFR #527882 CIA.GOV',
  'ETRSFR #226423 CIA.GOV',
  'ETRSFR #7486534 CIA.GOV',
  'ETRSFR #18965 CIA.GOV',
  'ETRSFR #1345643 CIA.GOV',
  'ETRSFR #424 CIA.GOV',
  'ETRSFR #1214427612 CIA.GOV',
  'ETRSFR #865834 CIA.GOV',
  'ETRSFR #5342543 CIA.GOV',
  'APPLE SOFTWARE X PAY MASSIVE',
  'GOOGLE SOFTWARE D PAY MEDIUM',
  'REXALL MARKETING L PAY SMALL',
  'ROMAINE LETTUCE STOCKS',
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.ORG`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.COM`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.NET`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.ORG`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.COM`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.NET`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.ORG`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.COM`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.NET`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.ORG`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.COM`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.NET`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.ORG`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.COM`,
  `ETRSFR #${faker.random.number()} ${faker.company.companyName().toUpperCase()}.NET`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
  `CRYPTO WITHDRAWAL #${faker.internet.ipv6()} ${(faker.animal.type()).toUpperCase()}COIN`,
];